# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: npm
  directory: "/"
# decides when to pull the dependencies
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
#tells what are all the dependencies to ignore
  ignore:
  - dependency-name: electron
    versions:
    - ">= 0"
  - dependency-name: electron-settings
    versions:
    - ">= 0"
  - dependency-name: less
    versions:
    - ">= 0"
